[build]
builder = "nixpacks"

[deploy]
startCommand = "flask db upgrade && gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 'app:create_app()'"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
FLASK_ENV = "production"
PYTHONUNBUFFERED = "1"
FLASK_APP = "app"
